name: kata
version: 0.0.0.0
license: CC0-1.0
author: Ryan Mulligan et al.
maintainer: ryan@ryantm.com
copyright: 2018-2019 Ryan Mulligan et al.
extra-source-files:
- README.md

github: ryantm/hkata

ghc-options:
  -Wall

dependencies:
  - base >= 4.16 && < 5
  - containers
  - deepseq
executables:
  hkata:
    main: Kata.hs

tests:
  doctests:
    main: Test.hs
    ghc-options: -threaded
    dependencies:
      - doctest
